---
driver:
  # you can restore this if you want, but it'll be slooooooow
  #name: vagrant
  name: docker
  # https://github.com/test-kitchen/kitchen-docker/issues/207
  use_sudo: false
driver_config:
  binary: /usr/local/bin/docker
  # install latest if not present
  require_chef_omnibus: true

provisioner:
  # it would be nice if this supported multiple provisioners (ordered) like vagrant does...
  #name: shell
  name: chef_solo

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: debian-8.9
  - name: debian-9.2
  - name: centos-6.9
  - name: centos-7.4

suites:
  - name: default
    run_list:
      - recipe[anaconda::default]
    attributes:
      anaconda:
        flavor: 'x86_64'
        accept_license: 'yes'
  - name: nbservice
    run_list:
      - recipe[anaconda::default]
    attributes:
      anaconda:
        flavor: 'x86_64'
        accept_license: 'yes'
